server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: assistant-gpt
    version: @project.version@
  profiles:
    active: @profile.active@

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.endlessovo.assistantGPT.model.entity
  type-aliases-super-type: java.lang.Object
#  type-enums-package: com.endlessovo.assistantGPT.model.entity
  #项目启动时检查 xml 配置的存在
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    aggressive-lazy-loading: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: none
    call-setters-on-nulls: true   #允许在resultType="map"时映射null值
#    打开 SQL log
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    multiple-result-sets-enabled: false
  global-config:
    db-config:
      table-underline: false
      id-type: ASSIGN_ID
      capital-mode: false
      logic-not-delete-value: 0 # 未删除
      logic-delete-value: 1 # 已删除